# Generated by Django 3.1.1 on 2020-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
