# Generated by Django 3.1.1 on 2020-09-05 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(max_length=400, null=True)),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=properties.models.upload_location)),
                ('view_count', models.IntegerField(default=0)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField(null=True)),
                ('order_message', models.TextField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, validators=[properties.models.phone_validator])),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
