# Generated by Django 3.1.1 on 2020-09-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproperty',
            old_name='order_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='orderproperty',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderproperty',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='orderproperty',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='property',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('message', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_property', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_datetime', models.DateTimeField()),
                ('message', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspect_property', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspect_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
