# Generated by Django 3.1.1 on 2020-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200914_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('sell', 'sell'), ('rent', 'rent')], default='sell', max_length=20),
        ),
    ]
