# Generated by Django 3.1.1 on 2020-09-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200915_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-timestamp']},
        ),
    ]
