# Generated by Django 3.1.1 on 2020-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200916_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectproperty',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
