# Generated by Django 3.1.2 on 2020-10-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200918_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectproperty',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Inspected Properties'},
        ),
        migrations.AlterModelOptions(
            name='orderproperty',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Ordered Properties'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='rentproperty',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Rented Properties'},
        ),
    ]
